### ISSUE TITLE
who wants to maintain and take ownership of the npm package

### ISSUE THREAD

**Issue by SPAHI4** [conundrumer/material-ui-mdi#1]

**Comment by conundrumer** [comment]
updated

In the future, I plan to stop using material-ui (because it uses inline styles), so there will come a point I'll stop maintaining this package.

**Comment by conundrumer** [comment]
@SPAHI4 do you want me to transfer the npm package ownership to you?

**Comment by conundrumer** [comment]
@vrtxf do you want to take ownership of the npm package

**Comment by 0-vortex** [comment]
@conundrumer if you don't want to manage it sure. I didn't mean to take over, I was stuck between 2 dependencies (icons and material-ui) and I found neither of them to be working at the time. I was planning on fixing the package, testing it and commit to a react boilerplate (that is private ATM), then propose a PR to your main package (like changing name, matching version with material-ui and improving documentation a bit). 
I kept you as author and added myself as contributor in package.json but for some reason it didn't display properly. I'll have an answer if it's fully working by tomorrow ! :D

**Comment by conundrumer** [comment]
@gabriel-miranda what about you

**Comment by gabriel-miranda** [comment]
@conundrumer I would love to. However I plan to modify a little the package so it doesnt depend anymore on material-ui when you need to use it (but i'll use it to create the icons, this would end up solving troubles as server-side rendering and the need of `navigator.userAgent`).
What do you think about that?

**Comment by conundrumer** [comment]
@vrtxf @gabriel-miranda @gilesbradshaw this issue is still open

also, @gabriel-miranda, making it `material-ui` independent sounds good. that dependency is the main reason this package keeps getting forked, i believe. will it still exist as a react component?

EDIT: ok the latest fork was to get updated icons. i wonder if there's a way to automatically update the npm package whenever new icons get added.

**Comment by 0-vortex** [comment]
I have my fork at 1 minor away from latest version I can update, clean it up and open a pull request. They changed some of the component names around and most of my work was to update the dev dependencies to be able to call the generator again. 
Material-ui independent version sounds very good by the way !

**Comment by gabriel-miranda** [comment]
Hi, tomorrow I'm doing my own package Probably will be called `isomorphic-material-icons` or something like that. The major changes are:
- You still need the `material-ui` package to create the svgs (and you depend on the material-ui api) but you no longer need the dependency after you install `material-ui-mdi`. No longer peer dependency needed
- You no longer need to specify `global.navigator` on node environments because all the prefixing can be done with something like PostCSS
- You must provide a prop of `size` for the viewbox of your icon
- You now have a `className` prop to style it (based on the issue with prefixing for browsers)

**Comment by conundrumer** [comment]
@SPAHI4 @vrtxf @gabriel-miranda

gonna deprecate this package bc I got a new package up that:
1. has no dependencies at all
2. auto-updates daily (as long as my home server is up)

lmk what you guys think: https://github.com/conundrumer/mdi-svg
